### ISSUE TITLE
Handle EACCES for stderr streams

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/atom-linter#109]
When processing text on the `stderr` stream (`{stream: 'stderr'}` or `{stream: 'both'}`), we should still handle `EACCES` errors.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/atom-linter/pull/106

**Comment by Arcanemagus** [comment]
How does #106 handle this? It isn't calling `handleError` on the `stderr` stream contents, and there is no passthrough in `handleError()` for when we are expecting content...

**Comment by steelbrain** [comment]
I'm unable to repro this, here's what I did in dev tools to repro

```js
var helpers = require('atom-linter')
helpers.exec('asdasd').catch(e => console.log(e))
helpers.exec('asdasd', [], {stream: 'stdout'}).catch(e => console.log(e))
helpers.exec('asdasd', [], {stream: 'stderr'}).catch(e => console.log(e))
helpers.exec('asdasd', [], {stream: 'both'}).catch(e => console.log(e))
```

All four of above work flawlessly for me

**Comment by Arcanemagus** [comment]
![image](https://cloud.githubusercontent.com/assets/427137/13261253/17beaa9a-da14-11e5-8c5b-ed39d05e6774.png)

Maybe this is Windows only? The last two fail for me.

**Comment by steelbrain** [comment]
Yo @Arcanemagus, is it still reproable?
