### ISSUE TITLE
(question) catching linter errors

### ISSUE THREAD

**Issue by mschuchard** [steelbrain/atom-linter#128]
When using `atom-linter` to execute a linter (e.g. eslint, rubocop, flake8) on the file currently being edited, as in the way most of the linters are doing (`return helpers.exec(atom.config.get('linterExecutablePath'), args, {stream: 'stdout'}).then(output => {`), is there any way to catch errors thrown by the linter?

I skimmed index.js and nothing jumped out at me.

**Comment by steelbrain** [comment]
`.catch(function(error) {  console.log(error); throw error })`
It returns a promise, it's easy to chain promises
Check out [`Promise`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise) on mdn

**Comment by steelbrain** [comment]
Also `linterExecutablePath` is an invalid config key, it should be `package-name.linterExecutablePath`

**Comment by mschuchard** [comment]
Thanks for the tip. I basically need this so that python IOError is ignored. It does not seem that Javascript is robust enough to handle something that granular, but I will try to figure out if and how to get this working.

> Also linterExecutablePath is an invalid config key, it should be package-name.linterExecutablePath

Yeah I was trying to write general 'foo' code and apparently failed.
