### ISSUE TITLE
Possible environment issue introduced in v4.7.0

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/atom-linter#129]
In https://github.com/AtomLinter/linter-scalac/pull/46 `linter-scalac` is having issues on it's AppVeyor CI build due to `scalac` not being found: https://ci.appveyor.com/project/andystanton/linter-scalac-3ymif/build/32

From the [build history](https://ci.appveyor.com/project/andystanton/linter-scalac-3ymif/history) it looks like this is a new issue.

**Comment by Arcanemagus** [comment]
Hmmm, another failure that looks like it might be caused by v4.7.0: https://ci.appveyor.com/project/Arcanemagus/linter-phpcs/build/68

**Comment by steelbrain** [comment]
If I had to guess it's the long standing https://github.com/nodejs/node-v0.x-archive/issues/2318
I'll be fixing this in `sb-exec`

**Comment by steelbrain** [comment]
Note to self: A similar work is done in [`linter-gsgl`](https://github.com/AtomLinter/linter-glsl/blob/d7daeef72cea1cb7b2ad4bc29e72c075cb57a9fc/lib/linter-glsl.js#L218-L227)

**Comment by steelbrain** [comment]
A fix is up in https://github.com/steelbrain/exec/pull/9
@Arcanemagus can you please confirm it fixes this?

**Comment by Arcanemagus** [comment]
As mentioned in https://github.com/AtomLinter/linter-php/issues/152#issuecomment-216319812, it looks like:

----

>We can fix the specs in packages by updating `atom-linter` from
>```js
export { exec, execNode } from 'sb-exec'
```
>to
>```js
import { exec, execNode } from 'sb-exec'
export { exec, execNode }
```
