### ISSUE TITLE
Check exit code

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/atom-linter#131]
We should be checking the exit code of applications, so if they exit with a `1` and we aren't expecting output on `stderr` something gets thrown back to the caller to notify that _something_ is wrong.

Of course with how badly most linters are written there probably needs to be a flag to ignore that as well...

**Comment by steelbrain** [comment]
Please note that due to structure of the stuff, we'll only be able to show exitCode for `stream: 'both'`

**Comment by steelbrain** [comment]
To be closed when `sb-exec` version is bumped to include https://github.com/steelbrain/exec/issues/14

**Comment by steelbrain** [comment]
`sb-exec` version `2.0.0` is out, we should bump it in this module with a major version release
