### ISSUE TITLE
atom-linter 5.x breaking linter

### ISSUE THREAD

**Issue by mschuchard** [steelbrain/atom-linter#139]
After updating the atom-linter dependency from 4.7.0 to 5.0.2, I had a linter package break with the following stack trace:

```
Error: Process exited with non-zero code: 2
    at ChildProcess.<anonymous> (node_modules/atom-linter/node_modules/sb-exec/lib/index.js:46:22)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

I checked the release notes for the `sb-exec` breaking change and modified my exec accordingly to:

```
return helpers.exec(executable, args, {cwd: path.dirname(file), allowEmptyStderr: true}).then(output => {
```

but the same stack trace resulted.

**Comment by steelbrain** [comment]
You can set `ignoreExitCode` to `true` to ignore the error code monitoring

**Comment by mschuchard** [comment]
Thanks, that fixed the issue. Maybe add that to the doc/release notes?

**Comment by steelbrain** [comment]
https://github.com/steelbrain/atom-linter/wiki/Migration-Guide#api-v4---api-v5

**Comment by mschuchard** [comment]
Updated.

**Comment by steelbrain** [comment]
Thanks but I thought we already had
```
Handling of return codes implemented, potentially breaking providers of linters that don't follow common best practices.
```
But I guess the new addition doesn't hurt 😅

**Comment by mschuchard** [comment]
I don't know where that line is from to be honest.

I am a polyglot, so I use something like twenty plus linters, and the exit code '2' for raised issues during the linting is actually somewhat common from what I have observed. I don't know if I would consider it best practices or not, but it certainly is common use.

**Comment by steelbrain** [comment]
Oh I was referring to the Upgrade Guide doc
