### ISSUE TITLE
Kill spawned process

### ISSUE THREAD

**Issue by halohalospecial** [steelbrain/atom-linter#142]
Hi :-)

Basically, what I want to do is to kill the current process and spawn a new one.  Is there a way to kill (or "replace") the process spawned by helpers.exec()?

Thanks!

**Comment by steelbrain** [comment]
Hi @halohalospecial :)

I'm afraid that's not possible yet, is there any particular reason you want to terminate the previous process? Because at the moment if you spawn a process with `helpers.exec()`, the base linter will simply ignore the previous invocation's results and use the latest

**Comment by halohalospecial** [comment]
Hi,

I'm linting on the fly, and want to kill the first process when I need to lint again (since the result of the first will not be applicable anymore).  It's mostly optimization, I guess, but not a showstopper.  Thanks for the quick response!

**Comment by steelbrain** [comment]
`kill()` method has been added in [`sb-exec@3.1.0`](https://github.com/steelbrain/exec/blob/master/CHANGELOG.md#310) and will be available in `atom-linter@8.1.0` (will be released soon).

Also note that any new atom-linter installation will automatically include that newer sb-exec version
