### ISSUE TITLE
Use 1-indexed numbers for invalid ranges?

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/atom-linter#147]
Should the error messages show 1-indexed values instead of 0-indexed? When I originally wrote the message I was only thinking about linter package authors, but it's users that most often see the message so it might make more sense to use 1-indexed values.

**Comment by steelbrain** [comment]
If it shows 1-indexed numbers for invalid ranges, it'll actually only add to the confusion. As the developers will not know if it's 0-indexed or 1-indexed. At least I would be

**Comment by steelbrain** [comment]
How about a hint in the message saying that the range displayed is a 0-indexed one?

**Comment by Arcanemagus** [comment]
This is getting trapped and handled differently by providers handling this "nicely" so it's not really relevant there, I think this is fine as is since we are requiring 0-indexed values to be input.
