### ISSUE TITLE
Rename rangeFromLineNumber

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/atom-linter#150]
We should rename `rangeFromLineNumber` in the next major release to something more accurate, I'm proposing "generateRange", but am open to suggestions 😉.

When originally written this function took just an editor and a line number, and generated a range encompassing the entire line. When the function was expanded with support for providing a column to narrow down the range we really should have renamed it then, but it was put off for ease of backwards compatibility.

Unfortunately the name really doesn't reflect the current capabilities of the function, and as a side bit is incredibly long to type.

**Comment by marionebl** [comment]
Could this even become a distinct package, say `@atom-linter/generate-range`? Given this package avoids a direct dependency on `atom` that would help with unit testing `linter-*` packages (as opposed to the `apm test` integration tests).

**Comment by Arcanemagus** [comment]
> Given this package avoids a direct dependency on atom that would help with unit testing linter-* packages (as opposed to the apm test integration tests).

I'm not entirely sure I understand what you are getting at by this, could you elaborate?
