### ISSUE TITLE
Upgrade parse to Message v2

### ISSUE THREAD

**Issue by Positive07** [steelbrain/atom-linter#166]
Currently `parse` returns a list of messages which correspond to the [Message v1 spec](https://github.com/steelbrain/linter/blob/v1/docs/types/linter-message-v1.md). It would be nice to update to the [new version of the spec](https://github.com/steelbrain/linter/blob/master/docs/types/linter-message-v2.md)

The current implementation returns:
```js
messages.push({
  type,
  text,
  filePath: file,
  range: [
    [lineStart > 0 ? lineStart - 1 : 0, colStart > 0 ? colStart - 1 : 0],
    [lineEnd > 0 ? lineEnd - 1 : 0, colEnd > 0 ? colEnd - 1 : 0],
  ],
})
```
The change would be something like:
```js
messages.push({
  excerpt: text,
  severity: type,
  location: {
    file: file,
    position: [
      [lineStart > 0 ? lineStart - 1 : 0, colStart > 0 ? colStart - 1 : 0],
      [lineEnd > 0 ? lineEnd - 1 : 0, colEnd > 0 ? colEnd - 1 : 0],
    ],
  },
})
```

Note that using `type` as `severity` may be wrong, but it is on the developers of each package to fix this issue. And as stated in #85 most active linters aren't using `parse`.

**Comment by Arcanemagus** [comment]
Personally I think `parse` should just be removed entirely, it's far too limited in what it supports, and virtually every usage of it requires additional "massaging" to get usable messages out of it, leading to the actual benefit of using it being almost none.

**Comment by Positive07** [comment]
Yeah maybe split it out into a really slim module (for those old linters that use it like Luacheck)

**Comment by Arcanemagus** [comment]
Closing for the reasoning in https://github.com/steelbrain/atom-linter/issues/166#issuecomment-296792034.
