### ISSUE TITLE
Configurable timeout

### ISSUE THREAD

**Issue by Rotonen** [steelbrain/atom-linter#174]
Motivation: I'm routinely having a file linted for over 10s on a larger project.

https://github.com/4teamwork/opengever.core

Using pylama / pylint on the stack of our product -> Plone -> CMF -> Zope -> ZTK -> ZCA -> ZODB routinely legitimately takes something in the order of magnitude of 15s .. 20s per larger file linted (~140k lines of Python in the product itself, ~1,5M lines of Python in the dependencies - pylint churns through stuff like method resolution order consistency on the deep and wide inheritance chains / networs thereof).

Being able to configure a timeout would be rather nice for me.

**Comment by Arcanemagus** [comment]
As the README states:

> For full documentation of `exec` and `execNode` API, please refer to [`sb-exec README`](https://github.com/steelbrain/exec/blob/master/README.md)

Going there leads to the [API](https://github.com/steelbrain/exec/blob/master/README.md#api) which shows that you can just specify a timeout in `ms`:

```js
atomLinter.exec(command, args, { timeout: 60000 });
```
