### ISSUE TITLE
Support Trace named captures.

### ISSUE THREAD

**Issue by keplersj** [steelbrain/atom-linter#36]
It'd be very handy to have Trace captures pulled out and handled correctly. Here's [an example](https://regex101.com/r/rF2pI4/3) that I'm working with for `linter-gradle`.

**Comment by steelbrain** [comment]
If we would capture a trace like that, would we be support filePath and ranges and text in traces, or just text?

**Comment by k2b6s9j** [comment]
Just text, I'd think. It just needs to be a simple implantation. If someone wants something more complex it probably needs tuning to their environment.
